# default provisioning for all vagrant boxes

$install_dotfiles = <<EOF
    wget -q https://github.com/janek-warchol/sensible-dotfiles/archive/master.tar.gz
    mkdir -p .dotfiles
    tar xf master.tar.gz --directory .dotfiles --strip-components=1
    .dotfiles/link-dotfiles.sh
    rm -f master.tar.gz
EOF

Vagrant.configure(2) do |config|
    config.vm.provision "shell", inline: $install_dotfiles, privileged: false
end

